### ISSUE TITLE
Pre-commit autoupdate workflow failing with app not found

### ISSUE THREAD

**Issue by tp832944** [gchq/Vanguard#176]
### What's the problem?

The generate a token step of Pre-commit autoupdate is failing with a Not Found error.

This might be due to using self-hosted runners or might be because an app hasn't been installed for Vanguard.

### How can we reproduce the issue?

https://github.com/gchq/Vanguard/actions/runs/9047502022/job/24859549631

### Python version

3.9

### Relevant log output

Run actions/create-github-app-token@v1
  with:
    app-id: 862378
    private-key: ***
    github-api-url: https://api.github.com
  env:
    config_path: .pre-commit-config.yaml
    update_message_path: /tmp/message.txt
    update_branch: chore/pre-commit-autoupdate
owner and repositories not set, creating token for the current repository ("Vanguard")
Failed to create token for "Vanguard" (attempt 1): Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
Failed to create token for "Vanguard" (attempt 2): Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
Failed to create token for "Vanguard" (attempt 3): Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
Failed to create token for "Vanguard" (attempt 4): Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
RequestError [HttpError]: Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
    at /home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:36627:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hook4 (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:39032:18)
    at async getTokenFromRepository (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:39352:20)
    at async RetryOperation._fn (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:39228:24) {
  status: 404,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/gchq/Vanguard/installation',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/create-github-app-token',
      authorization: 'bearer [REDACTED]'
    },
    request: { hook: [Function: bound hook4] AsyncFunction }
  },
  response: {
    url: 'https://api.github.com/repos/gchq/Vanguard/installation',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sun, 12 May 2024 00:35:36 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'EC63:1F205F:8A04125:E040993:66400ED3',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app'
    }
  },
  attemptNumber: 4,
  retriesLeft: 0
}
Error: Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app

**Comment by tp832944** [comment]
Ran successfully over the weekend.
